// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-DigitalTurbineBidding",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-DigitalTurbineBidding", targets: ["AATKit-DigitalTurbineBidding"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-GraviteRTB.git", exact: "3.18.0-beta3"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-DigitalTurbineBidding",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    .product(name: "AATKit-GraviteRTB", package: "AATKit-GraviteRTB"),
                    "AATDigitalTurbineBiddingAdapter",
                    "AATIASDKCore",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-DigitalTurbineBidding"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATDigitalTurbineBiddingAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/AATDigitalTurbineBiddingAdapter.zip",
            checksum: "d5a5283bbce5500ec5e7a434b7e2f1be0fc7fcb0815b2c23d64b07d7b901b679"
        ),
        .binaryTarget(
            name: "AATIASDKCore",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/IASDKCore.zip",
            checksum: "1ce0cec0428e7ffe34f41be67722bcef9cc5cfe5ff36f636c6494821d3e007b4"
        ),
    ]
)
